[build]
  command = "DOCUSAURUS_BASE_URL=/docs/ npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  DOCUSAURUS_BASE_URL = "/docs/"

# 1) Root -> /docs/
[[redirects]]
  from = "/"
  to   = "/docs/"
  status = 301

# 2) If someone hits /docs (no trailing slash), add it
[[redirects]]
  from = "/docs"
  to   = "/docs/"
  status = 301

# 3) Anything *not* starting with /docs gets mapped into /docs/…
#    e.g. /introducing-scribe/... -> /docs/introducing-scribe/...
[[redirects]]
  from = "/*"
  to   = "/docs/:splat"
  status = 301
  force = true