name: import


on:
  workflow_dispatch:
  push:

jobs:
  import_docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # TODO: only build
        repo: ["gensbom", "valint", "actions", "JSL", "misc"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p sub

      - uses: actions/checkout@v3
        with:
          repository: scribe-security/${{ matrix.repo }}
          path: sub/${{ matrix.repo }}
          token: ${{ secrets.PR_PAT }}
      
      - name: impor docs
        run: |
          bash scripts/sync_docs.sh -I -x -r ${{ matrix.repo }}
          bash scripts/sync_docs.sh -S || true
          git status
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: docs_import
          title: autogen - docs import
          token: ${{ secrets.GITHUB_TOKEN }}