name: export

# env:
#   GITHUB_USER: "houdini91" # TODO CHANGE TO A SCRIBE USER.
#   GOPRIVATE: "github.com/scribe-security/*"
#   GO_VERSION: "1.18"

on:
  workflow_dispatch:

jobs:
  export_docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # TODO: only build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      # - run: |
      #     bash scripts/sync_docs.sh -E
      #     bash scripts/sync_docs.sh -S
      - run: |
          mkdir -p subs

      - uses: actions/checkout@v3
        with:
          repository: scribe-security/JSL
          path: subs/JSL
          token: ${{ secrets.PR_PAT }}
      
      - run: |
          ls -lh
          bash scripts/sync_docs.sh -E -x -r JSL

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: subs/JSL
          token: ${{ secrets.PR_PAT }}
          title: autogen - docs export